FEATURE: Discourse Gamification backfill scores
discourse/discourse-gamification pull request #103
Opened 2023-07-18 16:08 UTC by rngus2344

2023-07-18 17:25 UTC, rngus2344 commented
'Recalculate Scores' button:
<img width="1096" alt="Screenshot 2023-07-18 at 12 09 21 PM" src="https://github.com/discourse/discourse-gamification/assets/70915823/150f101b-2512-455f-adbb-8051fc589bb7">

Recalculate range options:
<img width="515" alt="Screenshot 2023-07-18 at 12 12 30 PM" src="https://github.com/discourse/discourse-gamification/assets/70915823/1ede87a1-42d7-4e5a-8097-8e9c1aebfb35">
<img width="515" alt="Screenshot 2023-07-18 at 12 12 37 PM" src="https://github.com/discourse/discourse-gamification/assets/70915823/48d235a8-df61-4e05-bc34-c439241e47e3">
<img width="515" alt="Screenshot 2023-07-18 at 12 12 42 PM" src="https://github.com/discourse/discourse-gamification/assets/70915823/b737f807-113f-4e5f-9791-8495362e53dc">
<img width="515" alt="Screenshot 2023-07-18 at 12 12 55 PM" src="https://github.com/discourse/discourse-gamification/assets/70915823/1397d6fa-6541-4886-a871-fa33e230731b">
<img width="515" alt="Screenshot 2023-07-18 at 12 13 01 PM" src="https://github.com/discourse/discourse-gamification/assets/70915823/d3cfa8ec-31c0-4151-b7c1-b663b956fa8b">

For 'Custom Range', 'Apply' is not available when there is no input:
<img width="515" alt="Screenshot 2023-07-18 at 12 13 06 PM" src="https://github.com/discourse/discourse-gamification/assets/70915823/d44c98fb-3d49-4b1a-971c-669d5a4a7efa">
<img width="515" alt="Screenshot 2023-07-18 at 12 13 14 PM" src="https://github.com/discourse/discourse-gamification/assets/70915823/9544ef5f-dbb6-4ede-a3c4-3c4888531a35">

When you click 'Apply', daily recalculation remaining goes down and it tells admin when it's completed: 
<img width="515" alt="Screenshot 2023-07-18 at 12 14 45 PM" src="https://github.com/discourse/discourse-gamification/assets/70915823/84ac6b67-a003-4d1d-81e2-594279cae3a0">

When daily recalculation remaining is 0, 'Apply' button is not available:
<img width="515" alt="Screenshot 2023-07-18 at 12 15 14 PM" src="https://github.com/discourse/discourse-gamification/assets/70915823/2536f3eb-a964-4c1a-9ef0-5a92ef4806e9">
<img width="515" alt="Screenshot 2023-07-18 at 12 15 07 PM" src="https://github.com/discourse/discourse-gamification/assets/70915823/09f1268f-fd87-4fb9-9a43-7ed9dd20507d">

2023-07-20 21:16 UTC, xfalcox commented on jobs/regular/recalculate_scores.rb
> +    def execute(opts = { since: "2014-8-26" })
Why this date?

And if we need something, maybe default to 10.days.ago like the default?

2023-07-20 21:18 UTC, xfalcox requested changes
Please change the default job date.

2023-07-20 21:21 UTC, xfalcox commented
@ellaestigoy can you please give a pass on the modal ? I feel like spacing is a bit off, specially with the date.

2023-07-20 21:22 UTC, xfalcox commented on jobs/regular/recalculate_scores.rb
> +      ::MessageBus.publish "/recalculate_scores",
Can this message be sent only to the user who started the recalculation?

2023-07-25 01:25 UTC, ellaestigoy commented
> @ellaestigoy can you please give a pass on the modal ? I feel like spacing is a bit off, specially with the date.

Agreed, I'll check it locally first.

2023-07-25 20:41 UTC, ellaestigoy submitted a review, later dismissed

2023-07-25 20:41 UTC, ellaestigoy commented on assets/javascripts/discourse/components/modal/recalculate-scores-form.hbs
> +          <div>{{i18n "gamification.update_scores_help"}}</div>
Can we add a class name here, `recalculate-modal__lead-text` (we use BEM for naming) so we can target it for styling.

2023-07-25 20:41 UTC, ellaestigoy commented on assets/javascripts/discourse/components/modal/recalculate-scores-form.hbs
> +            <div class="date-range">
Can we rename it to `recalculate-modal__date-range` (we use BEM for naming).

2023-07-25 20:41 UTC, ellaestigoy commented on assets/javascripts/discourse/components/modal/recalculate-scores-form.hbs
> +    <div class="remaining">{{remainingText}}</div>
💅🏼 Can we rename it to `recalculate-modal__footer-text`

2023-07-25 21:13 UTC, ellaestigoy commented on assets/javascripts/discourse/components/modal/recalculate-scores-form.hbs
> +      <div class="status">{{d-icon "check"}}
💅🏼 Can we rename it to `recalculate-modal__status`?

2023-07-25 21:19 UTC, ellaestigoy commented on config/locales/client.en.yml
> +      completed: "Successfully done!"
Let's make the copy clearer, "Done! The scores have been successfully recalculated."

2023-07-26 16:44 UTC, rngus2344 commented
Okay, I made those changes! Please let me know if there's any other issues!

2023-07-26 17:50 UTC, xfalcox approved these changes

2023-07-26 17:50 UTC, merged